Repository yalla-coop/chiltern-music-therapy, pull requests merged in 2021-04, with the labels that each got.

#93 40 > Create Modal
  client/src/components/Button/Button.stories.js
  client/src/components/Button/index.js
  client/src/components/Button/style.js
  client/src/components/Modal/Modal.stories.js
  client/src/components/Modal/index.js
  client/src/components/Modal/style.js
  client/src/helpers/set-margin.js
  client/src/theme/index.js
Labels: awaiting-review

#94 fix grid gutters
  client/src/components/Grid/style.js
  client/src/theme/index.js
Labels: awaiting-review

#95 fix set margins helper
  client/src/helpers/set-margin.js
Labels: awaiting-review

#91 39 tag component
  client/src/components/Tag/Tag.stories.js
  client/src/components/Tag/index.js
  client/src/components/Tag/style.js
Labels: awaiting-review

#98 44 therapist sign up
  client/src/App.js
  client/src/components/GoBack/index.js
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/context/auth.js
  client/src/pages/Therapist/Signup/index.js
  client/src/pages/Therapist/Signup/style.js
  client/src/pages/Therapist/index.js
  client/src/validation/create-schema.js
  client/src/validation/custom-funtions.js
  client/src/validation/err-msgs.js
  client/src/validation/fields.js
  client/src/validation/index.js
  client/src/validation/schemas/index.js
  client/src/validation/schemas/login.js
  client/src/validation/schemas/signup.js
  client/src/validation/validate.js
  server/modules/user/controllers/signup.js
  server/modules/user/model/create.js
  server/modules/user/use-cases/therapist-signup.js
  server/modules/user/utils/validate-signup.js
  server/services/error-handler/messages.js
  server/services/validation/fields.js
  server/services/validation/validate.js
Labels: request-changes

#96 36 create navbar and menu
  client/src/App.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/General/style.js
  client/src/components/Layout/Onboarding/index.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/Navbar/Navbar.stories.js
  client/src/components/Navbar/index.js
  client/src/components/Navbar/style.js
  client/src/constants/nav-routes.js
  client/src/constants/roles.js
Labels: awaiting-review

#90 Set up Example component > #71
  client/src/components/Example/Example.stories.js
  client/src/components/Example/index.js
  client/src/components/Example/style.js
  client/src/components/Grid/style.js
Labels: awaiting-review

#99 41 > Cards
  client/package.json
  client/src/components/Cards/Basic/index.js
  client/src/components/Cards/Basic/style.js
  client/src/components/Cards/Cards.stories.js
  client/src/components/Cards/Expandable/index.js
  client/src/components/Cards/Expandable/style.js
  client/src/components/Cards/Link/index.js
  client/src/components/Cards/Link/style.js
  client/src/components/Cards/index.js
  client/src/components/Icon/icons/Edit.js
  client/src/components/Icon/index.js
  client/src/components/Image/index.js
  client/src/components/Typography/index.js
  client/src/components/assets/BlueCircles.svg
  client/src/components/assets/GreenCircles.svg
  client/src/components/assets/OrangeCircles.svg
  client/src/components/assets/PinkCircles.svg
  client/src/helpers/dateFormatter.js
  client/src/helpers/index.js
Labels: awaiting-review

#104 46 login / logout
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Navbar/NavRoutes.js
  client/src/constants/nav-routes.js
  client/src/context/auth.js
  client/src/pages/General/Login/index.js
  client/src/pages/General/Login/style.js
  client/src/pages/General/index.js
  server/api/middlewares/authenticate.js
  server/api/middlewares/authorize.js
  server/config/server.js
  server/constants/common.js
  server/database/build.js
  server/database/init/add-refs.sql
  server/database/init/index.js
  server/database/models/media/schema.sql
  server/helpers/create-test-token.js
  server/helpers/create-token.js
  server/modules/user/model/create.js
  server/modules/user/model/find.js
Labels: awaiting-review

#107 97 client dashboard front and therapist dashboard frontend
  client/src/App.js
  client/src/components/Cards/Basic/index.js
  client/src/components/Layout/General/style.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/Dashboard/index.js
  client/src/pages/Client/Dashboard/style.js
  client/src/pages/Client/index.js
  client/src/pages/Therapist/Dashboard/ClientsSection.js
  client/src/pages/Therapist/Dashboard/index.js
  client/src/pages/Therapist/Dashboard/style.js
  client/src/pages/Therapist/index.js
  client/src/theme/gradients.js
Labels: awaiting-review

#100 45 client sign up
  client/src/App.js
  client/src/api-calls/therapists-clients.js
  client/src/components/Icon/icons/Info.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/Signup/index.js
  client/src/pages/Client/Signup/style.js
  client/src/pages/Client/index.js
  client/src/validation/err-msgs.js
  client/src/validation/fields.js
  client/src/validation/schemas/signup.js
  server/api/index.js
  server/constants/data-type.js
  server/database/dummy-data/therapist-clients.js
  server/database/dummy-data/users.js
  server/database/models/therapist-clients/schema.sql
  server/database/models/users/schema.sql
  server/modules/therapist-client/controllers/get-therapist-by-invite-token.js
  server/modules/therapist-client/controllers/index.js
  server/modules/therapist-client/model/find.js
  server/modules/therapist-client/use-cases/get-therapist-by-invite-token.js
  server/modules/therapist-client/use-cases/index.js
  server/modules/user/controllers/signup.js
  server/modules/user/model/find.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/client-signup.js
  server/modules/user/utils/validate-signup.js
  server/services/error-handler/messages.js
  server/services/validation/fields.js
Labels: request-changes

#106 59 > My Programmes
  client/src/App.js
  client/src/api-calls/programmes.js
  client/src/components/Cards/Link/index.js
  client/src/components/Cards/Link/style.js
  client/src/components/Layout/General/style.js
  client/src/components/Title/Title.stories.js
  client/src/components/Title/index.js
  client/src/components/Typography/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/AllProgrammes/index.js
  client/src/pages/Client/index.js
  client/src/theme/index.js
  server/modules/programme/controllers/get-programmes-by-client.js
  server/modules/programme/controllers/index.js
  server/modules/programme/model/find.js
  server/modules/programme/use-cases/get-programmes-by-client.js
  server/modules/programme/use-cases/index.js
  server/modules/therapist-client/use-cases/get-therapist-client-by-client.js
Labels: awaiting-review

#105 fix avatar component
  client/src/components/Avatar/index.js
  client/src/components/Avatar/style.js
Labels: awaiting-review

#108 58 therapist details
  client/src/App.js
  client/src/api-calls/therapists-clients.js
  client/src/components/Avatar/style.js
  client/src/components/Grid/index.js
  client/src/components/Grid/style.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/Layout.stories.js
  client/src/components/Layout/Onboarding/index.js
  client/src/components/assets/Avatar.svg
  client/src/constants/nav-routes.js
  client/src/pages/Client/MyTherapist/ContactDetails.js
  client/src/pages/Client/MyTherapist/index.js
  client/src/pages/Client/MyTherapist/style.js
  client/src/pages/Client/index.js
  client/src/pages/General/Login/index.js
  package-lock.json
  package.json
  server/database/dummy-data/index.js
  server/database/dummy-data/media.js
  server/database/dummy-data/update-refs.js
  server/database/models/therapist-clients/schema.sql
  server/modules/therapist-client/controllers/get-my-therapist.js
  server/modules/therapist-client/controllers/index.js
  server/modules/therapist-client/model/find.js
  server/modules/therapist-client/use-cases/get-my-therapist.js
  server/modules/therapist-client/use-cases/index.js
  server/services/files-storage/get-file-pre-signed-url.js
  server/services/files-storage/index.js
Labels: awaiting-review

#109 Client and Therapist dashboard
  client/src/api-calls/users.js
  client/src/components/Cards/Basic/index.js
  client/src/components/Cards/Link/index.js
  client/src/helpers/getInitials.js
  client/src/helpers/index.js
  client/src/pages/Client/AllProgrammes/index.js
  client/src/pages/Client/Dashboard/index.js
  client/src/pages/Client/Dashboard/style.js
  client/src/pages/Therapist/Dashboard/ClientsSection.js
  client/src/pages/Therapist/Dashboard/index.js
  server/database/dummy-data/users.js
  server/modules/therapist-client/model/find.js
  server/modules/therapist-client/use-cases/get-clients-by-therapist.js
  server/modules/therapist-client/use-cases/get-therapist-by-client.js
  server/modules/therapist-client/use-cases/get-therapist-client-by-client.js
  server/modules/therapist-client/use-cases/index.js
  server/modules/user/controllers/get-user-dashboard.js
Labels: awaiting-review

#102 Edit card
  client/src/components/Cards/Cards.stories.js
  client/src/components/Cards/Expandable/EditMode.js
  client/src/components/Cards/Expandable/ViewMode.js
  client/src/components/Cards/Expandable/index.js
  client/src/components/Cards/Expandable/style.js
  client/src/components/Icon/index.js
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Typography/index.js
Labels: awaiting-review

#110 55, 56 therapy plan page , therapy goals page
  client/src/App.js
  client/src/api-calls/therapists-clients.js
  client/src/components/Layout/General/index.js
  client/src/components/Layout/General/style.js
  client/src/pages/Client/MyTherapyGoals/index.js
  client/src/pages/Client/MyTherapyGoals/style.js
  client/src/pages/Client/MyTherapyPlan/index.js
  client/src/pages/Client/index.js
  server/modules/therapist-client/controllers/get-my-therapy.js
  server/modules/therapist-client/controllers/index.js
  server/modules/therapist-client/model/find.js
  server/modules/therapist-client/use-cases/get-my-therapy.js
  server/modules/therapist-client/use-cases/index.js
Labels: awaiting-review

#112 47 therapist can add profile(front end)
  client/src/App.js
  client/src/api-calls/therapists-clients.js
  client/src/components/Cards/Link/index.js
  client/src/constants/nav-routes.js
  client/src/helpers/cleanEmail.js
  client/src/helpers/index.js
  client/src/pages/Therapist/Profile/index.js
  client/src/pages/Therapist/index.js
  client/src/validation/custom-functions.js
  client/src/validation/custom-funtions.js
  client/src/validation/err-msgs.js
  client/src/validation/fields.js
  client/src/validation/schemas/index.js
  client/src/validation/schemas/profile.js
Labels: awaiting-review

#118 Add option to add new
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Inputs/Inputs.stories.js
Labels: awaiting-review

#116 49 email setup
  client/src/constants/nav-routes.js
  package-lock.json
  package.json
  server/config/emails.js
  server/config/index.js
  server/constants/app-links.js
  server/constants/index.js
  server/modules/programme/index.js
  server/modules/programme/model/find.js
  server/modules/progress-update/model/find.js
  server/modules/therapist-client/model/find.js
  server/modules/user/use-cases/client-signup.js
  server/services/emails/index.js
  server/services/emails/template-keys.js
  server/services/emails/templates/client.signup-invite.js
  server/services/emails/templates/client.therapist-created-programme.js
  server/services/emails/templates/client.therapist-respond-to-progress-update.js
  server/services/emails/templates/client.therapist-updated-programme.js
  server/services/emails/templates/index.js
  server/services/emails/templates/therapist.client-sent-programme-feedback.js
  server/services/emails/templates/therapist.client-sent-progress-update.js
  server/services/emails/utils.js
  server/services/events/event-types.js
  server/services/events/index.js
  server/services/events/programme.js
  server/services/events/progress-update.js
  server/services/events/therapist-client.js
  server/services/events/user.js
Labels: approved, awaiting-review

#121 Create welcome screens
  client/src/App.js
  client/src/components/Layout/Info/index.js
  client/src/components/Layout/Info/style.js
  client/src/components/Route/index.js
  client/src/components/Title/index.js
  client/src/constants/content.js
  client/src/constants/index.js
  client/src/constants/nav-routes.js
  client/src/pages/General/Welcome/index.js
  client/src/pages/General/Welcome/style.js
  client/src/pages/General/index.js
  client/src/pages/Therapist/Dashboard/ClientsSection.js
  client/src/pages/Therapist/Profile/index.js
  client/src/theme/global-style.js
Labels: awaiting-review

#114 Therapist & Admin Library
  client/src/App.js
  client/src/api-calls/contents.js
  client/src/api-calls/users.js
  client/src/components/Cards/Expandable/EditMode.js
  client/src/components/Cards/Expandable/ViewMode.js
  client/src/components/Cards/Expandable/index.js
  client/src/components/Inputs/Dropdown/index.js
  client/src/components/Tag/index.js
  client/src/components/Tag/style.js
  client/src/constants/data-types.js
  client/src/helpers/decideBorder.js
  client/src/helpers/index.js
  client/src/pages/Therapist/Library/index.js
  client/src/pages/Therapist/Library/style.js
  client/src/pages/Therapist/index.js
  client/src/theme/index.js
  server/modules/content/controllers/get-categories.js
  server/modules/content/controllers/get-library-content.js
  server/modules/content/controllers/index.js
  server/modules/content/model/find.js
  server/modules/content/use-cases/get-categories.js
  server/modules/content/use-cases/get-library-content.js
  server/modules/content/use-cases/index.js
  server/modules/user/controllers/get-therapists.js
  server/modules/user/controllers/index.js
  server/modules/user/model/find.js
  server/modules/user/use-cases/get-therapists.js
  server/modules/user/use-cases/index.js
Labels: request-changes

#120 72 i can add a client front
  client/src/App.js
  client/src/api-calls/therapists-clients.js
  client/src/components/Cards/TherapyGoals/index.js
  client/src/components/Cards/TherapyGoals/style.js
  client/src/components/Copy/index.js
  client/src/pages/Therapist/AddClient/Step1.js
  client/src/pages/Therapist/AddClient/Step2.js
  client/src/pages/Therapist/AddClient/Step3.js
  client/src/pages/Therapist/AddClient/Step4.js
  client/src/pages/Therapist/AddClient/Step5.js
  client/src/pages/Therapist/AddClient/Step6.js
  client/src/pages/Therapist/AddClient/index.js
  client/src/pages/Therapist/index.js
  client/src/validation/err-msgs.js
  client/src/validation/fields.js
  client/src/validation/schemas/addClient.js
  client/src/validation/schemas/index.js
Labels: awaiting-review

#129 fix issue on home programme passing user id
  client/src/api-calls/programmes.js
  client/src/pages/Client/AllProgrammes/index.js
  client/src/pages/Client/Dashboard/index.js
Labels: awaiting-review

#127 76 delete user account
  client/src/App.js
  client/src/api-calls/users.js
  client/src/components/Cards/Link/index.js
  client/src/constants/data-types.js
  client/src/constants/index.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/DeleteAccount/AccountDeleted.js
  client/src/pages/Client/DeleteAccount/index.js
  client/src/pages/Client/DeleteAccount/style.js
  client/src/pages/Client/index.js
  client/src/pages/Therapist/SingleClient/index.js
  server/app.js
  server/database/dummy-data/media.js
  server/database/dummy-data/progress-updates.js
  server/database/models/users/schema.sql
  server/modules/media/model/find.js
  server/modules/media/model/remove.js
  server/modules/media/use-cases/delete-media-by-id.js
  server/modules/media/use-cases/index.js
  server/modules/progress-update/model/remove.js
  server/modules/progress-update/use-cases/delete-progress-update-by-id.js
  server/modules/progress-update/use-cases/index.js
  server/modules/therapist-client/model/find.js
  server/modules/therapist-client/use-cases/get-client-by-id.js
  server/modules/therapist-client/use-cases/get-clients-by-therapist.js
  server/modules/user/model/remove.js
  server/modules/user/use-cases/delete-user.js
  server/services/emails/template-keys.js
  server/services/emails/templates/client.account-deleted.js
  server/services/emails/templates/index.js
  server/services/emails/templates/therapist.client-account-deleted.js
  server/services/events/event-types.js
  server/services/events/index.js
  server/services/events/listeners.js
  server/services/events/media.js
  server/services/events/progress-update.js
  server/services/events/user.js
  server/services/files-storage/delete-file.js
  server/services/files-storage/index.js
Labels: awaiting-review

#123 50 reset password
  client/src/App.js
  client/src/api-calls/users.js
  client/src/components/Cards/Basic/index.js
  client/src/components/Cards/Basic/style.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/Dashboard/index.js
  client/src/pages/General/ForgotPassword/index.js
  client/src/pages/General/Login/index.js
  client/src/pages/General/ResetPassword/index.js
  client/src/pages/General/index.js
  client/src/validation/err-msgs.js
  client/src/validation/fields.js
  client/src/validation/schemas/forgotPassword.js
  client/src/validation/schemas/index.js
  client/src/validation/schemas/updatePassword.js
  server/constants/app-links.js
  server/database/models/users/schema.sql
  server/modules/user/controllers/index.js
  server/modules/user/controllers/reset-password-link.js
  server/modules/user/controllers/update-password.js
  server/modules/user/model/find.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/index.js
  server/modules/user/use-cases/reset-password-link.js
  server/modules/user/use-cases/update-password.js
  server/modules/user/utils/index.js
  server/modules/user/utils/validate-password.js
  server/services/emails/template-keys.js
  server/services/emails/templates/index.js
  server/services/emails/templates/user.reset-password.js
  server/services/error-handler/messages.js
  server/services/events/event-types.js
  server/services/events/user.js
  server/services/validation/fields.js
Labels: awaiting-review

#125 Create Program: Bugfix routing, validation fix, adding content categories and library
  client/src/App.js
  client/src/api-calls/contents.js
  client/src/components/Cards/Basic/index.js
  client/src/components/Cards/Expandable/EditMode.js
  client/src/components/Cards/Expandable/index.js
  client/src/components/Content/AddContentSection/index.js
  client/src/components/Content/AddSingleContent/index.js
  client/src/pages/Therapist/CreateProgram/AddContent.js
  client/src/pages/Therapist/CreateProgram/AddDescription.js
  client/src/pages/Therapist/CreateProgram/ReviewFinish.js
  client/src/pages/Therapist/CreateProgram/actionTypes.js
  client/src/pages/Therapist/CreateProgram/index.js
  client/src/pages/Therapist/CreateProgram/reducer.js
  server/modules/content/model/find.js
  server/modules/programme/use-cases/create-programme.js
  server/modules/therapist-client/model/find.js
Labels: awaiting-review

#133 130 create single programme page for therapist
  client/src/App.js
  client/src/components/Cards/Basic/index.js
  client/src/constants/nav-routes.js
  client/src/helpers/dateFormatter.js
  client/src/pages/Therapist/IndividProgramme/UpdateSection.js
  client/src/pages/Therapist/IndividProgramme/index.js
  client/src/pages/Therapist/IndividProgramme/style.js
  client/src/pages/Therapist/index.js
Labels: awaiting-review

#136 69 > View Programme as Therapist (BACK)
  client/src/components/Inputs/Dropdown/index.js
  client/src/pages/Client/IndividProgramme/index.js
  client/src/pages/Therapist/IndividProgramme/index.js
  server/modules/content/model/find.js
  server/modules/programme/model/find.js
Labels: awaiting-review

#137 68 > Edit & Remove Content in Library
  client/src/api-calls/contents.js
  client/src/components/Modal/index.js
  client/src/pages/Therapist/Library/index.js
  client/src/validation/schemas/editContent.js
  client/src/validation/schemas/index.js
  server/modules/content/controllers/delete-content.js
  server/modules/content/controllers/edit-content.js
  server/modules/content/controllers/index.js
  server/modules/content/controllers/remove-content-from-library.js
  server/modules/content/model/create.js
  server/modules/content/model/find.js
  server/modules/content/model/remove.js
  server/modules/content/model/update.js
  server/modules/content/use-cases/delete-content.js
  server/modules/content/use-cases/edit-content.js
  server/modules/content/use-cases/index.js
  server/modules/content/use-cases/remove-content-from-library.js
  server/services/error-handler/messages.js
  server/services/events/event-types.js
  server/services/events/media.js
Labels: awaiting-review

#139 64 create program backend
  client/src/components/Cards/Expandable/EditMode.js
  client/src/components/Cards/Expandable/style.js
  client/src/components/FileUpload/index.js
  client/src/components/Inputs/Dropdown/index.js
  client/src/helpers/createUniqueCats.js
  client/src/helpers/index.js
  client/src/helpers/isEmptyObject.js
  client/src/pages/Therapist/CreateProgram/ReviewFinish.js
  client/src/pages/Therapist/CreateProgram/Success.js
  client/src/pages/Therapist/CreateProgram/actionTypes.js
  client/src/pages/Therapist/CreateProgram/index.js
  client/src/pages/Therapist/CreateProgram/reducer.js
  client/src/pages/Therapist/IndividProgramme/UpdateSection.js
  client/src/pages/Therapist/IndividProgramme/index.js
  client/src/pages/Therapist/Library/index.js
  client/src/pages/Therapist/SingleClient/index.js
  client/src/theme/borders.js
  server/database/models/contents/schema.sql
  server/modules/content/model/create.js
  server/modules/content/model/find.js
  server/modules/content/model/update.js
  server/modules/media/model/create.js
  server/modules/media/use-cases/index.js
  server/modules/programme/controllers/get-programme-by-id.js
  server/modules/programme/model/create.js
  server/modules/programme/model/find.js
  server/modules/programme/use-cases/create-programme.js
  server/modules/programme/utils/index.js
  server/modules/programme/utils/match-media-types.js
  server/modules/therapist-client/model/find.js
  server/services/files-storage/index.js
  server/services/validation/fields.js
Labels: awaiting-review

#140 35 media streaming
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/components/Video/Video.stories.js
  client/src/components/Video/index.js
  client/src/theme/global-style.js
Labels: awaiting-review

#132 73 > Add Client (BACK)
  client/src/api-calls/therapists-clients.js
  client/src/api-calls/users.js
  client/src/pages/Therapist/AddClient/Step1.js
  client/src/pages/Therapist/AddClient/Step2.js
  client/src/pages/Therapist/AddClient/Step3.js
  client/src/pages/Therapist/AddClient/Step4.js
  client/src/pages/Therapist/AddClient/Step5.js
  client/src/pages/Therapist/AddClient/Step6.js
  client/src/pages/Therapist/AddClient/index.js
  client/src/validation/schemas/addClient.js
  server/app.js
  server/database/models/therapist-clients/schema.sql
  server/modules/therapist-client/controllers/create-therapist-client.js
  server/modules/therapist-client/controllers/index.js
  server/modules/therapist-client/model/create.js
  server/modules/therapist-client/use-cases/create-therapist-client.js
  server/modules/therapist-client/use-cases/index.js
  server/modules/therapist-client/utils/index.js
  server/modules/therapist-client/utils/validate-create-client.js
  server/modules/user/controllers/check-user-exists.js
  server/modules/user/controllers/index.js
  server/modules/user/model/create.js
  server/modules/user/model/find.js
  server/modules/user/use-cases/check-user-exists.js
  server/modules/user/use-cases/index.js
  server/services/error-handler/messages.js
  server/services/validation/fields.js
Labels: awaiting-review

#134 74 > Edit Client Notes
  client/src/App.js
  client/src/api-calls/therapists-clients.js
  client/src/components/Cards/TherapyGoals/index.js
  client/src/components/Cards/TherapyGoals/style.js
  client/src/components/Modal/index.js
  client/src/pages/Therapist/EditClient/index.js
  client/src/pages/Therapist/EditClient/style.js
  client/src/pages/Therapist/SingleClient/ClientHistory.js
  client/src/pages/Therapist/index.js
  client/src/validation/schemas/editClient.js
  server/database/dummy-data/therapist-clients.js
  server/modules/therapist-client/controllers/edit-therapist-client-by-id.js
  server/modules/therapist-client/controllers/index.js
  server/modules/therapist-client/model/update.js
  server/modules/therapist-client/use-cases/edit-therapist-client-by-id.js
  server/modules/therapist-client/use-cases/index.js
Labels: approved

#145 documents download and content
  client/src/components/Cards/Expandable/EditMode.js
  client/src/components/Cards/Expandable/ViewMode.js
  client/src/components/Cards/Expandable/index.js
  client/src/components/Video/index.js
  client/src/pages/Client/IndividProgramme/index.js
  client/src/pages/Therapist/AddClient/Step1.js
  client/src/pages/Therapist/AddClient/Step2.js
  client/src/pages/Therapist/AddClient/Step3.js
  client/src/pages/Therapist/AddClient/Step4.js
  client/src/pages/Therapist/CreateProgram/ReviewFinish.js
  client/src/pages/Therapist/IndividProgramme/index.js
  client/src/pages/Therapist/Library/index.js
  client/src/theme/global-style.js
  server/database/dummy-data/contents-content-categories.js
  server/database/dummy-data/contents.js
  server/database/dummy-data/media.js
  server/database/dummy-data/programmes-contents.js
  server/modules/content/model/find.js
  server/modules/content/use-cases/get-content-by-prog.js
  server/modules/content/use-cases/get-library-content.js
  server/modules/content/utils/index.js
  server/modules/content/utils/set-contents-media-file-url.js
  server/services/files-storage/delete-file.js
Labels: awaiting-review

#144 61 send a progress update (front)
  client/src/App.js
  client/src/api-calls/progress-updates.js
  client/src/components/Cards/Expandable/ExpandableTitle.js
  client/src/components/Cards/Expandable/ViewMode.js
  client/src/components/Cards/Expandable/index.js
  client/src/components/Cards/Expandable/style.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/IndividProgramme/FeedbackSection.js
  client/src/pages/Client/IndividProgramme/UpdateSection.js
  client/src/pages/Client/SuccessUpdate/index.js
  client/src/pages/Client/Update/SendAudio.js
  client/src/pages/Client/Update/SendMessage.js
  client/src/pages/Client/Update/SendVideo.js
  client/src/pages/Client/Update/actionTypes.js
  client/src/pages/Client/Update/index.js
  client/src/pages/Client/Update/reducer.js
  client/src/pages/Client/index.js
  client/src/pages/Therapist/ViewUpdate/DocumentUpdate.js
  client/src/pages/Therapist/ViewUpdate/VideoUpdate.js
  client/src/pages/Therapist/ViewUpdate/index.js
  client/src/pages/Therapist/ViewUpdate/style.js
  client/src/pages/Therapist/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/document-update.js
  client/src/validation/schemas/index.js
  client/src/validation/schemas/therapist-message.js
  client/src/validation/schemas/videoUpdate.js
  package-lock.json
Labels: awaiting-review

#141 Set up Account Details
  client/package-lock.json
  client/src/App.js
  client/src/api-calls/users.js
  client/src/components/Avatar/index.js
  client/src/components/Avatar/style.js
  client/src/components/FileUpload/index.js
  client/src/components/Icon/index.js
  client/src/components/Modal/index.js
  client/src/components/Title/index.js
  client/src/components/Typography/index.js
  client/src/constants/content.js
  client/src/pages/Client/MyAccount/index.js
  client/src/pages/Client/index.js
  client/src/pages/Therapist/AddClient/Step4.js
  client/src/pages/Therapist/MyAccount/index.js
  client/src/pages/Therapist/index.js
  client/src/validation/schemas/account.js
  server/database/dummy-data/users.js
  server/modules/media/model/update.js
  server/modules/media/use-cases/index.js
  server/modules/media/use-cases/update-media-by-id.js
  server/modules/therapist-client/use-cases/create-therapist-client.js
  server/modules/user/controllers/get-account-info.js
  server/modules/user/controllers/index.js
  server/modules/user/controllers/update-account.js
  server/modules/user/model/find.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/get-account-info.js
  server/modules/user/use-cases/index.js
  server/modules/user/use-cases/update-account.js
  server/services/files-storage/config.js
Labels: awaiting-review

#151 Fix Style bugs
  client/src/components/Cards/Expandable/style.js
  client/src/components/Cards/Link/style.js
  client/src/components/FileUpload/style.js
  client/src/components/Title/index.js
  client/src/pages/Client/Dashboard/index.js
  client/src/pages/Client/IndividProgramme/FeedbackSection.js
  client/src/pages/Client/IndividProgramme/UpdateSection.js
  client/src/pages/Client/IndividProgramme/index.js
Labels: awaiting-review

#149 146 front end routing
  client/src/App.js
  client/src/components/Route/index.js
Labels: awaiting-review

#154 fix the navbar style
  client/src/components/Navbar/NavRoutes.js
Labels: awaiting-review

#155 Render account image
  client/src/pages/Therapist/MyAccount/index.js
Labels: request-changes

#160 47 > Create therapist profile
  client/src/App.js
  client/src/api-calls/users.js
  client/src/components/Route/index.js
  client/src/pages/Therapist/Profile/index.js
  client/src/pages/Therapist/Signup/index.js
  client/src/validation/schemas/profile.js
  server/api/middlewares/authenticate.js
  server/modules/user/controllers/create-therapist-profile.js
  server/modules/user/controllers/index.js
  server/modules/user/model/find.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/check-therapist-profile.js
  server/modules/user/use-cases/create-therapist-profile.js
  server/modules/user/use-cases/index.js
  server/modules/user/use-cases/login.js
  server/modules/user/use-cases/therapist-signup.js
  server/modules/user/use-cases/update-account.js
Labels: awaiting-review

#163 162 programmes order
  client/src/pages/Client/AllProgrammes/index.js
  client/src/pages/Therapist/EditProgramme/Review.js
  server/modules/programme/model/find.js
  server/modules/therapist-client/model/find.js
Labels: awaiting-review

#158 create context for extendable cards
  client/src/components/Cards/Expandable/EditMode.js
  client/src/components/Cards/Expandable/ViewMode.js
  client/src/components/Cards/Expandable/index.js
  client/src/context/expandable.js
  client/src/pages/Client/IndividProgramme/index.js
  client/src/pages/Client/Update/index.js
  client/src/pages/Therapist/CreateProgram/ReviewFinish.js
  client/src/pages/Therapist/EditProgramme/Review.js
  client/src/pages/Therapist/IndividProgramme/index.js
  client/src/pages/Therapist/Library/index.js
Labels: awaiting-review

#165 152 protect media url
  client/src/pages/Therapist/MyAccount/index.js
  client/src/pages/Therapist/Profile/index.js
  server/modules/media/use-cases/get-media-url.js
Labels: awaiting-review

#166 78 send feedback frontend
  client/src/App.js
  client/src/api-calls/programmes.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/Feedback/Q1.js
  client/src/pages/Client/Feedback/Q2.js
  client/src/pages/Client/Feedback/Q3.js
  client/src/pages/Client/Feedback/Q4.js
  client/src/pages/Client/Feedback/index.js
  client/src/pages/Client/index.js
  client/src/pages/General/SuccessFeedback/index.js
  client/src/pages/General/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/feedback.js
  client/src/validation/schemas/index.js
Labels: awaiting-review

#167 161 create update programme tests
  client/src/components/Content/AddSingleContent/index.js
  server/database/dummy-data/contents.js
  server/modules/content/controllers/delete-content.js
  server/modules/content/controllers/remove-content-from-programme.spec.js
  server/modules/content/use-cases/create-content.js
  server/modules/content/use-cases/delete-content.js
  server/modules/content/use-cases/remove-content-from-library.js
  server/modules/content/use-cases/remove-content-from-programme.js
  server/modules/programme/controllers/create-programme.js
  server/modules/programme/controllers/create-programme.spec.js
  server/modules/programme/controllers/index.js
  server/modules/programme/controllers/update-programme.spec.js
  server/modules/programme/use-cases/create-programme.js
  server/modules/programme/use-cases/update-programme.js
Labels: awaiting-review

#168 164 general bugs
  client/src/pages/Client/MyTherapist/index.js
  client/src/pages/Therapist/AddClient/Step4.js
  client/src/pages/Therapist/Dashboard/index.js
  client/src/pages/Therapist/MyAccount/index.js
  client/src/pages/Therapist/Profile/index.js
  client/src/pages/Therapist/SingleClient/ClientHistory.js
  client/src/pages/Therapist/SingleClient/index.js
  client/src/pages/Therapist/ViewUpdate/DocumentUpdate.js
  client/src/pages/Therapist/ViewUpdate/VideoUpdate.js
  client/src/pages/Therapist/ViewUpdate/index.js
  server/helpers/set-media-file-url.js
  server/modules/user/model/find.js
  server/modules/user/use-cases/get-account-info.js
  server/modules/user/use-cases/update-account.js
Labels: awaiting-review

#175 Fixes #174
  client/src/App.js
  client/src/pages/Client/Signup/index.js
  server/constants/app-links.js
  server/modules/user/model/find.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/client-signup.js
Labels: awaiting-review

#173 172 update cards bugs
  client/src/components/Cards/Expandable/index.js
  client/src/validation/err-msgs.js
  client/src/validation/fields.js
  server/modules/content/use-cases/create-content.js
Labels: awaiting-review

#176 send feedback backend
  client/src/api-calls/programmes.js
  client/src/pages/Client/Feedback/index.js
  client/src/pages/Therapist/AddClient/Step6.js
  server/database/models/programmes-feedback/schema.sql
  server/modules/programme/controllers/create-programme-feedback.js
  server/modules/programme/controllers/index.js
  server/modules/programme/model/create.js
  server/modules/programme/use-cases/create-programme-feedback.js
  server/modules/programme/use-cases/index.js
Labels: awaiting-review

#138 75 cookie
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
Labels: awaiting-review

#178 Production db 2
  package-lock.json
  package.json
  server/config/common.js
  server/database/dummy-data-prod/build.js
  server/database/dummy-data-prod/build.script.js
  server/database/dummy-data-prod/index.js
  server/database/dummy-data-prod/organisations.js
  server/database/dummy-data-prod/users.js
  server/modules/content/controllers/remove-content-from-programme.js
  server/modules/content/controllers/remove-content-from-programme.spec.js
  server/modules/content/model/find.js
  server/modules/content/model/update.js
  server/modules/content/use-cases/create-content.js
  server/modules/content/use-cases/delete-content.js
  server/modules/content/use-cases/get-library-content.js
  server/modules/content/use-cases/remove-content-from-library.js
  server/modules/content/use-cases/remove-content-from-programme.js
  server/modules/programme/controllers/create-programme.spec.js
  server/modules/programme/controllers/update-programme.spec.js
  server/modules/programme/use-cases/create-programme.js
  server/modules/programme/use-cases/manage-content-contents-categories.js
  server/modules/programme/use-cases/update-programme.js
  server/services/error-handler/sentry.js
Labels: awaiting-review

#203 Create contact client page
  client/src/App.js
  client/src/pages/Therapist/ContactClient/index.js
  client/src/pages/Therapist/index.js
  client/src/validation/fields.js
  server/modules/therapist-client/model/find.js
Labels: awaiting-review

#199 183 fix basic design bus
  client/src/components/Inputs/BasicInput/index.js
  client/src/components/Inputs/BasicInput/style.js
  client/src/constants/content.js
  client/src/pages/Client/MyTherapyGoals/index.js
  client/src/pages/General/SuccessFeedback/index.js
  client/src/pages/Therapist/AddClient/Step3.js
  client/src/pages/Therapist/MyAccount/index.js
  client/src/validation/fields.js
  client/src/validation/schemas/account.js
Labels: request-changes

#198 removed prompt
  client/src/App.js
  client/src/components/Content/AddSingleContent/index.js
  client/src/components/Content/AddSingleContent/style.js
  client/src/components/Content/index.js
  client/src/constants/nav-routes.js
  client/src/pages/General/HowToRecord/index.js
  client/src/pages/General/HowToRecord/style.js
  client/src/pages/General/index.js
  client/src/pages/Therapist/CreateProgram/flowTypes.js
  client/src/pages/Therapist/CreateProgram/index.js
  client/src/pages/Therapist/EditProgramme/flowTypes.js
  client/src/pages/Therapist/EditProgramme/index.js
Labels: awaiting-review

#202 upload bugfixes
  client/src/api-calls/media.js
  client/src/components/Cards/Expandable/EditMode.js
  client/src/components/Cards/Info/index.js
  client/src/components/Cards/Info/style.js
  client/src/components/Content/AddSingleContent/index.js
  client/src/components/FileUpload/index.js
  client/src/components/FileUpload/style.js
  client/src/constants/content.js
  client/src/pages/Therapist/CreateProgram/index.js
  client/src/pages/Therapist/EditProgramme/Review.js
  client/src/pages/Therapist/EditProgramme/index.js
  server/modules/media/use-cases/get-signed-url.js
  server/services/files-storage/config.js
  server/services/files-storage/get-signed-url.js
Labels: awaiting-review

#209 205 fix validation on profile page
  client/src/helpers/cleanEmail.js
  client/src/validation/fields.js
Labels: awaiting-review

#207 182 categories bugs
  client/src/components/Inputs/Dropdown/style.js
  client/src/validation/fields.js
  server/database/models/content-categories/schema.sql
  server/database/models/contents-content-categories/schema.sql
  server/modules/content/controllers/remove-content-from-programme.spec.js
  server/modules/content/model/create.js
  server/modules/content/model/find.js
  server/modules/content/model/remove.js
  server/modules/content/use-cases/create-categories.js
  server/modules/content/use-cases/create-content.js
  server/modules/content/use-cases/edit-content.js
  server/modules/content/use-cases/index.js
  server/modules/content/utils/get-unique-categories-from-contents.js
  server/modules/content/utils/index.js
  server/modules/programme/controllers/create-programme.spec.js
  server/modules/programme/controllers/update-programme.spec.js
  server/modules/programme/use-cases/create-programme.js
  server/modules/programme/use-cases/manage-content-contents-categories.js
  server/modules/programme/use-cases/update-programme.js
  server/services/events/content.js
  server/services/events/event-types.js
  server/services/events/listeners.js
  server/services/events/programme.js
  server/services/validation/fields.js
Labels: awaiting-review

#211 Fix therapy goals
  client/src/pages/Client/MyTherapyGoals/index.js
  client/src/pages/Therapist/SingleClient/ClientHistory.js
Labels: awaiting-review

#206 197 account del bug
  client/src/App.js
  client/src/constants/nav-routes.js
  client/src/pages/Client/DeleteAccount/index.js
  client/src/pages/Client/index.js
  client/src/pages/General/AccountDeletedSuccess/index.js
  client/src/pages/General/AccountDeletedSuccess/style.js
  client/src/pages/General/index.js
Labels: awaiting-review

#204 fix download bugs
  client/src/components/Cards/Expandable/ViewMode.js
  client/src/components/Cards/Expandable/style.js
Labels: awaiting-review

#213 208 bugfix
  client/src/pages/Therapist/AddClient/Step4.js
  client/src/pages/Therapist/Library/index.js
Labels: request-changes

#225 220 add phone numbers to client account
  client/src/pages/Client/MyAccount/index.js
  client/src/validation/schemas/account.js
  server/modules/user/model/find.js
  server/modules/user/model/update.js
  server/modules/user/use-cases/update-account.js
Labels: awaiting-review

#226 216 bugfix
  client/src/components/Content/AddSingleContent/index.js
  client/src/constants/content.js
  client/src/pages/Client/Update/SendAudio.js
  client/src/pages/Client/Update/SendVideo.js
  server/services/files-storage/config.js
Labels: awaiting-review

#224 general bugs
  client/src/App.js
  client/src/components/Layout/Onboarding/style.js
  client/src/components/Route/index.js
  client/src/helpers/ScrollToTop.js
  client/src/helpers/index.js
  client/src/pages/Client/MyTherapist/index.js
  client/src/pages/Therapist/SingleClient/ClientHistory.js
  client/src/pages/Therapist/SingleClient/index.js
Labels: request-changes

#232 Add Analytics and Remove Feedback
  client/package-lock.json
  client/package.json
  client/src/components/Cards/Expandable/index.js
  client/src/components/Navbar/NavRoutes.js
  client/src/components/Video/index.js
  client/src/index.js
  client/src/pages/Therapist/SingleClient/index.js
  server/modules/programme/use-cases/create-programme-feedback.js
Labels: awaiting-review

#235 Increase character limit on file type
  server/database/models/media/schema.sql
Labels: awaiting-review

#236 Add footer to emails > #233
  server/constants/content.js
  server/constants/index.js
  server/services/emails/templates/client.account-deleted.js
  server/services/emails/templates/client.signup-invite.js
  server/services/emails/templates/client.therapist-created-programme.js
  server/services/emails/templates/client.therapist-respond-to-progress-update.js
  server/services/emails/templates/client.therapist-updated-programme.js
  server/services/emails/templates/therapist.client-account-deleted.js
  server/services/emails/templates/therapist.client-sent-programme-feedback.js
  server/services/emails/templates/therapist.client-sent-progress-update.js
  server/services/emails/templates/user.reset-password.js
Labels: awaiting-review

#239 removed to lower case
  client/src/components/Content/AddSingleContent/index.js
  client/src/pages/Client/Update/SendAudio.js
  client/src/pages/Client/Update/SendVideo.js
Labels: awaiting-review

#237 show links as plain text
  server/services/emails/templates/client.signup-invite.js
  server/services/emails/templates/client.therapist-created-programme.js
  server/services/emails/templates/client.therapist-respond-to-progress-update.js
  server/services/emails/templates/client.therapist-updated-programme.js
  server/services/emails/templates/therapist.client-sent-programme-feedback.js
  server/services/emails/templates/therapist.client-sent-progress-update.js
  server/services/emails/templates/user.reset-password.js
Labels: awaiting-review

#240 add on delete cascade hook for prog_contents
  server/database/migrations/20210427103924-on-delete-cascade-for-programme-contents.js
  server/database/migrations/sqls/20210427103924-on-delete-cascade-for-programme-contents-down.sql
  server/database/migrations/sqls/20210427103924-on-delete-cascade-for-programme-contents-up.sql
  server/database/models/programmes-contents/schema.sql
  server/modules/content/model/remove.js
  server/modules/content/use-cases/delete-content.js
Labels: awaiting-review
